filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
repositories:
- name: jxgh
  url: https://jenkins-x-charts.github.io/repo
releases:
- chart: jxgh/jx-verify
  name: jx-verify
  namespace: jx-production
  values:
  - jx-values.yaml
templates: {}
renderedvalues: {}
